using System;
using System.Collections.Generic;
using System.Text;

namespace VeggieMobile21062018
{
    /*
     * 
     *  Author: Oscar Chambers - 29/06/2018
     *  This is the class that deals with the QR string generated by a receive request:
     *  The QR string has all the information needed to generate a receive address. 
     *  The important fields are address, amount, label and message.
     * 
     *  Example Usage:
     *  ReceiveQRStringParser receive = new ReceiveQRStringParser("bitcoin:P9UbvDiH95NRyfqPpXqwx9Be5Pun4CeV25?amount=444.66600000&label=This%20is%20an%20example%20label&message=An%20Example%20Message");
     *	Console.WriteLine("Address is: " + receive.GetAddress());
     *	Console.WriteLine("Amount is: " + receive.GetAmount());
     *	Console.WriteLine("Label is: " + receive.GetLabel());
     *	Console.WriteLine("Message is: " + receive.GetMessage());
     *
     */

    class ReceiveQRStringParser
    {
        private String address = "";
        private String amount = "";
        private String label = "";
        private String message = "";
        public ReceiveQRStringParser(String QrString)
        {
            SetAddressFromQrString(QrString);
            SetAmountFromQrString(QrString);
            SetLabelFromQrString(QrString);
            SetMessageFromQrString(QrString);
        }

        public String GetAddress()
        {
            return this.address;
        }

        public String GetAmount()
        {
            return this.amount;
        }

        public String GetLabel()
        {
            return this.label;
        }

        public String GetMessage()
        {
            return this.message;
        }


        private void SetAmountFromQrString(String QrString)
        {
            if (QrString.Contains("amount="))
            {
                int pFrom = QrString.IndexOf("amount=") + "amount=".Length;
                while (pFrom != QrString.Length - 1)
                {
                    this.amount += QrString[pFrom];
                    ++pFrom;
                    if (QrString[pFrom] == '&')
                    {
                        return;
                    }

                    if (pFrom == QrString.Length - 1)
                    {
                        this.amount += QrString[pFrom];
                    }
                }
            }
        }

        private void SetLabelFromQrString(String QrString)
        {
            if (QrString.Contains("label="))
            {
                int pFrom = QrString.IndexOf("label=") + "label=".Length;
                while (pFrom != QrString.Length - 1)
                {
                    this.label += QrString[pFrom];
                    ++pFrom;
                    if (QrString[pFrom] == '&')
                    {
                        return;
                    }

                    if (pFrom == QrString.Length - 1)
                    {
                        this.label += QrString[pFrom];
                        return;
                    }
                }
            }

        }

        private void SetMessageFromQrString(String QrString)
        {
            if (QrString.Contains("message="))
            {
                int pFrom = QrString.IndexOf("message=") + "message=".Length;
                while (pFrom != QrString.Length - 1)
                {
                    this.message += QrString[pFrom];
                    ++pFrom;
                    if (QrString[pFrom] == '&')
                    {
                        return;
                    }

                    if (pFrom == QrString.Length - 1)
                    {
                        this.message += QrString[pFrom];
                        return;
                    }
                }
            }
        }

        private void SetAddressFromQrString(String QrString)
        {
            this.address = QrString.Substring(8, 34);
        }
    }
}
